# docker compose v2 (docker-compose v1)
# docker compose build
# docker compose up -d
# docker compose exec web pip freeze
# docker compose exec web pip install numpy
# docker compose exec web pip install pyzk
# docker compose restart
# docker compose down -v
# docker ps -a
# docker rm $(docker ps -aq)
# docker compose exec web odoo scaffold openacademy1 /mnt/extra-addons
# docker exec -it odoo-container odoo scaffold openacademy2 /mnt/extra-addons
# docker exec -it odoo-container bash -c "odoo scaffold openacademy3 /mnt/extra-addons"
version: '3.1'
services:
  web:
    container_name: odoo-container
    image: odoo:17.0-20240812
    restart: always
    env_file: .env
    depends_on:
      - psql
    command: ["bash", "-c", "pip install numpy && pip install pyzk && odoo -c /etc/odoo/odoo.conf -u all"]
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./modules:/mnt/extra-modules
  # pgadmin:
  #   container_name: pgadmin-container
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   env_file: .env
  #   depends_on:
  #     - psql
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  psql:
    container_name: postgres-container
    image: postgres:latest
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  odoo-data:
  # pgadmin-data:
  postgres-data:
