from . import classroom
from . import field_of_study
from . import level
from . import semester
from . import subject
from . import teacher
from . import university
from . import year
from . import student_enrollment
from . import courses
