from . import batch
from . import classroom
from . import field_of_study
from . import level
from . import school
from . import calendar_event
from . import semester
from . import student
from . import subject
from . import teacher
from . import university
from . import year
from . import degree_course_required
from . import student_enrollment
from . import student
from . import courses
from . import fee_student
from . import fee_school
from . import country
from . import fee_enrollment
from . import register_enrollement
from . import country
from . import fee_student
from . import timetable
from . import partenaire
from . import class_division
from . import production_pe
from . import res_user
from . import menu
from . import hourly_rate
from . import daily_attendance
from . import exam_score
from . import hr_department
from . import biometric_device_details
from . import request_track
from . import general_setting
