[options]
admin_passwd = strong_admin_password
addons_path = /mnt/extra-addons,/mnt/extra-modules
data_dir = /var/lib/odoo
db_host = psql1
db_port = 5432
db_user = odoo117
db_password = odoo117
http_port = 8069
logrotate = True
proxy_mode = True
db_name = False
server_wide_modules = base,web
