from . import timetable_print_wizard
from . import teacher_print_wizard
from . import student_print_wizard
from . import daily_attendance_print_wizard
from . import classroom_print_wizard
from . import class_division_print_wizard
from . import subject_print_wizard
from . import progress_report_print_wizard
from . import timetable_wizard
from . import check_priority
from . import check_avaible_slot
from . import data_request_wizard
from . import timetable_filter_wizard
from . import classroom_filter_wizard
from . import class_division_filter_wizard
from . import teacher_filter_wizard
from . import student_filter_wizard
from . import daily_attendance_filter_wizard
from . import timetable_group_copy_wizard
from . import timetable_group_move_wizard
from . import subject_filter_wizard
from . import progress_report_filter_wizard
from . import class_ue_copy_wizard
