from . import timetable_print_wizard
from . import teacher_print_wizard
from . import student_print_wizard
from . import daily_attendance_print_wizard
from . import classroom_print_wizard
from . import class_print_wizard
from . import timetable_wizard
from . import check_priority
from . import check_avaible_slot
from . import data_request_wizard
from . import timetable_filter_wizard
from . import classroom_filter_wizard
from . import class_filter_wizard
from . import teacher_filter_wizard
from . import student_filter_wizard
from . import daily_attendance_filter_wizard
from . import timetable_group_copier_wizard
