from . import academic_year
from . import availability
from . import batch
from . import building
from . import classroom
from . import field_of_study
from . import level
from . import program
from . import resource_calendar
from . import schedule
from . import school
from . import semester
from . import student
from . import subject
from . import teacher
from . import timetable
